# kubernetes/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: trading-simulator
spec:
  replicas: 2
  selector:
    matchLabels:
      app: trading-simulator
  template:
    metadata:
      labels:
        app: trading-simulator
    spec:
      containers:
      - name: trading-simulator
        image: jamiecodes/trading-simulator:1.0
        ports:
        - containerPort: 5000  # Flask app port
        - containerPort: 8000  # Prometheus metrics port
        env:
        - name: PROD
          value: "1"
        resources:
          requests:
            cpu: "100m"  # 0.1 CPU
            memory: "128Mi"  # 128 MB RAM
          limits:
            cpu: "200m"  # 0.2 CPU
            memory: "256Mi"  # 256 MB RAM
    spec:
        template:
            spec:
                nodeSelector:
                    nodegroup: trading-nodes
            