apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: trading-simulator-monitor
  labels:
    release: prometheus 
spec:
  selector:
    matchLabels:
      app: trading-simulator
  endpoints:
  - port: metrics  
    interval: 15s