apiVersion: v1
kind: Service
metadata:
  name: trading-simulator-service
spec:
  selector:
    app: trading-simulator
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  type: LoadBalancer
